const strings = {
  login: 'Login',
  enter: 'Enter your mobile number to proceed',
  by: 'By counting you agree to our',
  terms: 'Terms of conditions,Privacy policy, Promotions T&C',
  Nutrition: "Nutrition Information",
  get_otp: "Get Otp",
  an_otp: "An OTP has been sent to",
  verify_otp: "Verify Otp",
  resend: "Re-send OTP",
  one_last: "One last thing",
  what_do: "What do we call you?",
  done: "Done",
  You_can: "You can always change",
  the_name: " the name in your order.",
  delivery: "DELIVERY",
  dine_in: "DINE-IN/TAKEAWAY",
  dine_in_at: "DINE-IN AT:",
  deliverTo: "DELIVER TO:",
  our_menu: "Our Menu",
  crown: "Crown Rewards",
  find_A_bk: "Find A Bk",
  recent: "Recent Orders",
  saved: "Saved Addresses",
  Saved_King: "Saved King Deals",
  Bk_wall: "BK Wall",
  faq: "FAQs & Support",
  Legal: "Legal Terms",
  Nutrition: "Nutrition Info",
  logout: "Logout",
  recentPage: "RECENT ORDERS",
  delivery_location: "Delivery Location",
  bk_recommended: "Bk Recommended"
};

export default strings;