const strings = {
  login: 'Login',
  enter: 'Enter your mobile number to proceed',
  by: 'By counting you agree to our',
  terms: 'Terms of conditions,Privacy policy, Promotions T&C',
  Nutrition: "Nutrition Information",
  get_otp: "Get Otp",
  an_otp: "An OTP has been sent to",
  verify_otp: "Verify Otp",
  resend: "Re-send OTP",
  one_last: "One last thing",
  what_do: "What do we call you?",
  done: "Done",
  You_can: "You can always change",
  the_name: " the name in your order.",
  delivery: "DELIVERY",
  dine_in: "DINE-IN/TAKEAWAY",
  dine_in_at: "DINE-IN AT:",
  deliverTo: "DELIVER TO:",
  our_menu: "Our Menu",
  crown: "Crown Rewards",
  find_A_bk: "Find A Bk",
  recent: "Recent Orders",
  saved: "Saved Addresses",
  Saved_King: "Saved King Deals",
  Bk_wall: "BK Wall",
  faq: "FAQs & Support",
  Legal: "Legal Terms",
  Nutrition: "Nutrition Info",
  logout: "Logout",
  recentPage: "RECENT ORDERS",
  delivery_location: "Delivery Location",
  bk_recommended: "Bk Recommended",
  goodFood:"Our restaurants are known for serving high-quality, great-tasting, and affordable food. Founded in 1954, BURGER KING® is the second largest fast food hamburger chain in the world with about 18,000 restaurants operating in more than 100 countries and US territories as at June 30, 2019. The original HOME OF THE WHOPPER®, our commitment to ingredients, signature recipes, and end-to-end online Burger King experience for millennials is what has defined our brand for more than 50 years.",
  youCan:"You can contact by writing to us at customercare@burgerking.in",
  doIneed:"Do I need to register to place an order?",
  yesyou:"Yes, you need to register on the Burger King Application (App)/ Burger King Website to place an order using your Mobile Number",
  whereIcan:"Where can I place the order online?",
  canPlace:"You can place an online order through Burger King Application (App)/ Burger King Website or food aggregator platform",
};

export default strings;