const Icon = {
    splace: require("/Users/user/Burgerking/src/assets/icons/splace.png"),
    leftArror: require("/Users/user/Burgerking/src/assets/icons/back.png"),
    menu: require("/Users/user/Burgerking/src/assets/icons/burger.png"),
    home: require("/Users/user/Burgerking/src/assets/icons/home.png"),
    crown: require("/Users/user/Burgerking/src/assets/icons/crown.png"),
    store: require("/Users/user/Burgerking/src/assets/icons/foodCart.png"),
    drawerIcon: require("/Users/user/Burgerking/src/assets/icons/bars.png"),
    storelocation: require("/Users/user/Burgerking/src/assets/icons/store.png"),
    locaton: require("/Users/user/Burgerking/src/assets/icons/map.png"),
    search: require("/Users/user/Burgerking/src/assets/icons/search.png"),
    orangeLeftArrow: require("/Users/user/Burgerking/src/assets/icons/left_arrow.png"),
    avitar: require("/Users/user/Burgerking/src/assets/icons/avitar.jpeg"),
    faq: require("/Users/user/Burgerking/src/assets/icons/faq.png"),
    clock: require("/Users/user/Burgerking/src/assets/icons/clock.png"),
    document: require("/Users/user/Burgerking/src/assets/icons/document.png"),
    logout: require("/Users/user/Burgerking/src/assets/icons/logout.png"),
    leaf: require("/Users/user/Burgerking/src/assets/icons/leaf.png"),
    notification: require("/Users/user/Burgerking/src/assets/icons/notification.png"),
    store_d: require("/Users/user/Burgerking/src/assets/icons/store_d.png"),
    wall: require("/Users/user/Burgerking/src/assets/icons/wall.png"),
    left_arrow: require("/Users/user/Burgerking/src/assets/icons/arrowDrawer.png"),
    star: require("/Users/user/Burgerking/src/assets/icons/star.png"),
    home_bk_wall: require("/Users/user/Burgerking/src/assets/icons/home_bk_wall.jpg"),
    paytm: require("/Users/user/Burgerking/src/assets/icons/paytmlogo.png"),
    gPay: require("/Users/user/Burgerking/src/assets/icons/google-pay.png"),
    card: require("/Users/user/Burgerking/src/assets/icons/credit-card.png"),
    rightArrow: require("/Users/user/Burgerking/src/assets/icons/right_arrow.png"),
    sbi: require("/Users/user/Burgerking/src/assets/icons/SBI.png"),
    hdfc: require("/Users/user/Burgerking/src/assets/icons/hdfc.png"),
    icici: require("/Users/user/Burgerking/src/assets/icons/icici.png"),
    axix: require("/Users/user/Burgerking/src/assets/icons/axis.png"),
    check: require("/Users/user/Burgerking/src/assets/check.png"),
    burgerOriginal: require("/Users/user/Burgerking/src/assets/icons/BurgerKingOrignal.png"),
    notificattionlogo:require("/Users/user/Burgerking/src/assets/icons/check_mark.png"),
    call:require("/Users/user/Burgerking/src/assets/icons/call.png"),
    location:require("/Users/user/Burgerking/src/assets/icons/location.png"),
    crownPoint:require("/Users/user/Burgerking/src/assets/icons/BurReward_Point.webp"),

}

export default Icon;